/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/spaceship.glb 
Author: L_Krajewski (https://sketchfab.com/L_Krajewski)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/soma04-spaceship-low-poly-exterior-9c4dd5eec2784b73ae2c8f39382f552e
Title: Soma04 spaceship low poly - exterior
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/spaceship.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Space_ship} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/spaceship.glb')
