/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/Astronaut-transformed.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function AstronautTransformed(props) {
  const { nodes, materials } = useGLTF("/astronaut.glb");

  const manRef = useRef();

  const adjustAstronaut = () => {
    let screenPosition, screenScale;

    if (window.innerWidth < 768) {
      screenPosition = [0, -10, -7];
      screenScale = 0.5;
    } else {
      screenPosition = [5, -10, -7];
      screenScale = 0.8;
    }
    return [screenPosition, screenScale];
  };

  const [astronautPosition, astronautScale] = adjustAstronaut();
  useFrame(() => {
    manRef.current.rotation.x += 0.005;
  });

  return (
    <group {...props} dispose={null} position={astronautPosition}>
      <group
        rotation={[-Math.PI / 2, 0, 0]}
        scale={astronautScale}
        ref={manRef}
      >
        <group
          position={[0.108, 1.44, 3.194]}
          rotation={[0.022, -0.019, -0.01]}
          scale={0.918}
        >
          <mesh
            geometry={nodes.Sphere008_0.geometry}
            material={materials.tuta_metallico}
          />
          <mesh
            geometry={nodes.Sphere008_1.geometry}
            material={materials.specchio}
          />
        </group>
        <mesh
          geometry={nodes.Cylinder002_0.geometry}
          material={materials.tuta_metallico}
          position={[0.113, 1.496, 3.313]}
          rotation={[0.022, -0.019, -0.01]}
          scale={0.867}
        />
        <mesh
          geometry={nodes.NurbsPath004_0.geometry}
          material={materials["tuta_metallico.001"]}
          position={[0.632, 0.09, 4.163]}
          rotation={[-0.526, -0.213, -1.309]}
          scale={0.355}
        />
        <mesh
          geometry={nodes.Plane005_0.geometry}
          material={materials.tuta_metallico}
          position={[0.099, 2.147, 3.085]}
          rotation={[1.593, -0.01, 0.019]}
          scale={[0.786, 1.012, 1.012]}
        />
        <mesh geometry={nodes.Plane006_0.geometry} material={materials.Root} />
        <mesh geometry={nodes.Sphere007_0.geometry} material={materials.Root} />
        <mesh
          geometry={nodes.Sphere009_0.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Sphere009_0001.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Sphere009_0002.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Sphere009_0003.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Sphere009_0004.geometry}
          material={materials["Material.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/astronaut.glb");
