/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/moon.glb 
Author: Akshat (https://sketchfab.com/shooter24994)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/moon-4db2273f6dd943b8ad7fa5e3b1b2431a
Title: Moon
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Moon(props) {
  const { nodes, materials } = useGLTF("/moon1.glb");

  const adjustMoon = () => {
    let screenPosition;

    if (window.innerWidth < 768) {
      screenPosition = [0.5, -11, 0];
    } else {
      screenPosition = [9, -9, 0];
    }
    return [screenPosition];
  };

  const [moonPosition] = adjustMoon();
  return (
    <group {...props} dispose={null} position={moonPosition}>
      <mesh
        geometry={nodes.pSphere1_lambert2_0.geometry}
        material={materials.lambert2}
        scale={8}
      />
    </group>
  );
}

useGLTF.preload("/moon1.glb");
